name: Packer Build

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOMAIN: ${{ vars.DOMAIN }}

jobs:
  validate-and-format:
    name: Validate and Format Packer Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Init Packer
        run: packer init .

      - name: Format Packer Script
        run: packer fmt .

      - name: Validate Packer Script
        run: packer validate .