name: Packer Build

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:

  build-ami:
    name: Build and Get AMI ID
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Packer build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var-file=variables.auto.pkrvars.hcl"
          target: main.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN: ${{ vars.DOMAIN }}
